name: Auto Priv Repo Demo

on:
  push:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. 
    # High load times include the start of every hour. 
    # To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    # Every 20 minutes.
    # - cron: '*/20 * * * *'
    # triggers the workflow every day at 5:20 UTC
    - cron: "20 5 * * *"


jobs:
  report:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repo code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
                python-version: '3.12'
                cache: 'pip'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Checkout private repo for product data
          uses: actions/checkout@v4
          with:
            repository: username/private-repo
            token: ${{ secrets.PRIVATE_REPO_TOKEN }}
            path: project/sdp

        - name: Fetch product infos
          run: python project/sdp/src/run.py
          working-directory: project/sdp

        - name: Generate report and update README
          run: |
            python project/sdp/src/generate_report.py --csv_path data/all-products.csv
            ls -l
            pwd
          working-directory: project/sdp

        # - name: Fetch product infos
        #   run: python src/run.py

        - name: Rename CSV with unique suffix
          id: rename_csv
          run: |
            pwd
            ls -l
            suffix=$(date +'%Y%m%d-%H%M%S')
            new_filename="data/all-products-${suffix}.csv"
            mv data/all-products.csv $new_filename
            # echo "::set-output name=csv_path::$new_filename"
            echo "csv_path=$new_filename" >> "$GITHUB_OUTPUT"

        # - name: Copy renamed CSV to original path
        #   run: cp ${{ steps.rename_csv.outputs.csv_path }} data/all-products.csv

        # - name: Generate report and update README
        #   run: python src/generate_report.py --csv_path data/all-products.csv

        - name: Update README with Markdown preview
          run: |
            echo "## Auto Sync Time" > README.md
            date >> README.md
            echo '## Annually Product Infos' >> README.md
            cat data/annually-products.md >> README.md            
            echo -e "## 💻 Open Source Work Stats \n![github stats](https://github-readme-stats.vercel.app/api?username=simwiki&show_icons=true)" >> README.md
            echo -e "## Star History \n[![Star History Chart](https://api.star-history.com/svg?repos=simwiki/easy-workflow&type=Date)](https://star-history.com/#simwiki/easy-workflow)" >> README.md

        - name: Commit and push updates
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add ${{ steps.rename_csv.outputs.csv_path }} README.md
            git commit -m "Update product report with latest data"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Archive markdown artifact
          uses: actions/upload-artifact@v4
          with:
            name: all-products-markdown
            path: data/all-products.md
            retention-days: 5
