name: Access Priv Repo Code Demo

on:
  push:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. 
    # High load times include the start of every hour. 
    # To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    # Every 20 minutes.
    # - cron: '*/20 * * * *'
    # triggers the workflow every day at 5:20 UTC
    # - cron: "20 5 * * *"
    # triggers the workflow at minute 20 past every 7th hour. https://crontab.guru/
    - cron: "20 */7 * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repo code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
                python-version: '3.12'
                cache: 'pip'

        - name: Install dependencies
          run: |
            pwd
            ls -l
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Checkout private repo for product data
          uses: actions/checkout@v4
          with:
            repository: simwiki/easy-code
            token: ${{ secrets.PRIVATE_REPO_TOKEN }}
            path: vpsrn

        - name: Fetch product infos
          run: |
            pwd
            ls -l
            ls -l ../data
            python project/sdp/src/run.py --data_dir ../data
          working-directory: vpsrn

        - name: Generate report and update README
          run: |
            python project/sdp/src/generate_report.py --data_dir ../data
          working-directory: vpsrn

        - name: Rename CSV with unique suffix
          id: rename_csv
          run: |
            pwd
            ls -l
            ls -l data
            suffix=$(date +'%Y%m%d-%H%M%S')
            new_filename="data/all-products-${suffix}.csv"
            cp data/all-products.csv $new_filename
            echo "csv_path=$new_filename" >> "$GITHUB_OUTPUT"
            ls -l

        - name: Copy renamed CSV to original path
          run: |
            pwd
            cp ${{ steps.rename_csv.outputs.csv_path }} data/all-products-test.csv
            ls -l

        - name: Update README with Markdown preview
          run: |
            echo "## Auto Sync Time" > README.md
            date >> README.md
            echo '## Annually Product Infos' >> README.md
            cat data/annually-products.md >> README.md
            echo -e "\n\n" >> README.md   
            echo -e "> [!TIP]" >> README.md
            echo -e "> :+1: [All annually vps lists](data/annually-products.md)\n" >> README.md
            # echo -e "\n\n :+1: [All annually vps lists](data/annually-products.md)\n" >> README.md        
            echo -e "\n---\n## 💻 Open Source Work Stats \n![github stats](https://github-readme-stats.vercel.app/api?username=simwiki&show_icons=true)" >> README.md
            echo -e "## Star History \n[![Star History Chart](https://api.star-history.com/svg?repos=simwiki/easy-workflow&type=Date)](https://star-history.com/#simwiki/easy-workflow)" >> README.md

        - name: Commit and push updates
          run: |
            git status
            git log --pretty=oneline | head -n 10
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add data/all-products.csv data/annually-products.md README.md
            git commit -m "[Bot] Auto Update Product Infos"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Archive markdown artifact
          uses: actions/upload-artifact@v4
          with:
            name: annually-products-markdown
            path: data/all-products.csv data/annually-products.md
            retention-days: 5
