name: Auto-Running Python Demo

on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repo code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
                python-version: '3.12'
                cache: 'pip'

        - name: Display Python version
          run: python -c "import sys; print(sys.version)"

        - name: Install dependencies
          run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install tabulate

        - name: Fetch product infos
          run: python src/run.py

        - name: Rename CSV with unique suffix
          id: rename_csv
          run: |
            suffix=$(date +'%Y%m%d-%H%M%S')
            new_filename="data/all-products-${suffix}.csv"
            mv data/all-products.csv $new_filename
            echo "::set-output name=csv_path::$new_filename"

        - name: Copy renamed CSV to original path
          run: cp ${{ steps.rename_csv.outputs.csv_path }} data/all-products.csv

        - name: Convert CSV to Markdown
          run: |
            python -c "
            import pandas as pd
            from tabulate import tabulate
            df = pd.read_csv('data/all-products.csv')
            markdown = tabulate(df, headers='keys', tablefmt='pipe')
            with open('data/all-products.md', 'w') as f:
                f.write(markdown)
            "

        - name: Update README with Markdown preview
          run: |
            echo '## Product Report\n\n' > README.md
            head -n 20 data/all-products.md >> README.md
            echo '\n\n...full report available in data/all-products.md' >> README.md
            echo "## Auto Sync Time" >> README.md
            date >> README.md
            echo -e "### 💻 Open Source Work Stats \n![github stats](https://github-readme-stats.vercel.app/api?username=simwiki&show_icons=true)" >> README.md
            echo -e "## Star History \n[![Star History Chart](https://api.star-history.com/svg?repos=simwiki/easy-workflow&type=Date)](https://star-history.com/#simwiki/easy-workflow)" >> README.md

        - name: Commit and push updates
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add data/all-products.csv ${{ steps.rename_csv.outputs.csv_path }} README.md
            git commit -m "Update product report with latest data"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Archive markdown artifact
          uses: actions/upload-artifact@v4
          with:
            name: all-products-markdown
            path: data/all-products.md
            retention-days: 5
